name: my_color_workflow
on:
  workflow_dispatch:
env:
  favorite_color: orange
jobs:
  set_colors:
    runs-on: ubuntu-latest
    env:
      favorite_color: blue
    steps:
      - name: Set the color
        id: step_one
        env:
          favorite_color: green
        run: |
          echo "my_color=$favorite_color" >> "$GITHUB_ENV"
      - name: echo the color
        id: step_two
        run: |
          echo $my_color
          echo $favorite_color
          echo "ðŸŽ‰ My color is ${{ env.my_color }}"
          echo "ðŸŽ‰ My favorite color is ${{ env.favorite_color }}"
  my_color_2:
    runs-on: ubuntu-latest
    steps:
      - name: echo the color
        id: step_one
        run: |
          cat ${{github.env}}
          echo ${{env.favorite_color}}
          echo ${{env.my_color}}
